package org.victoriaThreeShatterer.utils

enum class RegionalMapping(val literacy: String, val wealth: String, val technologyBase: String) {
    WEST_EUROPE(
        "effect_starting_pop_literacy_middling",
        "effect_starting_pop_wealth_medium",
        "effect_starting_technology_tier_1_tech"
    ),
    SOUTH_EUROPE(
        "effect_starting_pop_literacy_middling",
        "effect_starting_pop_wealth_medium",
        "effect_starting_technology_tier_2_tech"
    ),
    EAST_EUROPE(
        "effect_starting_pop_literacy_very_low",
        "effect_starting_pop_wealth_medium",
        "effect_starting_technology_tier_3_tech"
    ),
    NORTH_AFRICA(
        "effect_starting_pop_literacy_baseline",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_5_tech"
    ),
    SUBSAHARAN_AFRICA(
        "effect_starting_pop_literacy_baseline",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_6_tech"
    ),
    NORTH_AMERICAN(
        "effect_starting_pop_literacy_very_low",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_3_tech"
    ),
    CENTRAL_AMERICAN(
        "effect_starting_pop_literacy_very_low",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_4_tech"
    ),
    SOUTH_AMERICAN(
        "effect_starting_pop_literacy_very_low",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_5_tech"
    ),
    MIDDLE_EAST(
        "effect_starting_pop_literacy_very_low",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_4_tech"
    ),
    CENTRAL_ASIA(
        "effect_starting_pop_literacy_baseline",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_6_tech"
    ),
    INDIA(
        "effect_starting_pop_literacy_baseline",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_5_tech"
    ),
    EAST_ASIA(
        "effect_starting_pop_literacy_baseline",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_5_tech"
    ),
    INDONESIA(
        "effect_starting_pop_literacy_baseline",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_6_tech"
    ),
    AUSTRALASIA(
        "effect_starting_pop_literacy_very_low",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_3_tech"
    ),
    SIBERIA(
        "effect_starting_pop_literacy_very_low",
        "effect_starting_pop_wealth_low",
        "effect_starting_technology_tier_5_tech"
    )
}